const cardController = require('../Controllers/cardController');
const express = require('express');
const router = express.Router();
const auth = require("../Middlewares/auth");
router.delete('/:workspaceId/:boardId/:listId/:cardId/delete-card',   cardController.deleteById); router.put('/:workspaceId/:boardId/:listId/:cardId/update-cover',   cardController.updateCover);
router.put('/:workspaceId/:boardId/:listId/:cardId/:attachmentId/update-attachment',   cardController.updateAttachment);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:attachmentId/delete-attachment',   cardController.deleteAttachment); 
router.post('/:workspaceId/:boardId/:listId/:cardId/add-attachment',   cardController.addAttachment);
router.put('/:workspaceId/:boardId/:listId/:cardId/update-date-completed',   cardController.updateDateCompleted);
router.put('/:workspaceId/:boardId/:listId/:cardId/update-dates',   cardController.updateStartDueDates);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:checklistId/:checklistItemId/delete-checklist-item',   cardController.deleteChecklistItem);
router.put('/:workspaceId/:boardId/:listId/:cardId/:checklistId/:checklistItemId/set-checklist-item-text',   cardController.setChecklistItemText);
router.put('/:workspaceId/:boardId/:listId/:cardId/:checklistId/:checklistItemId/set-checklist-item-completed',   cardController.setChecklistItemCompleted);
router.post('/:workspaceId/:boardId/:listId/:cardId/:checklistId/add-checklist-item',   cardController.addChecklistItem);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:checklistId/delete-checklist',   cardController.deleteChecklist);
router.post('/:workspaceId/:boardId/:listId/:cardId/create-checklist',   cardController.createChecklist);
router.put('/:workspaceId/:boardId/:listId/:cardId/:labelId/update-label-selection',   cardController.updateLabelSelection);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:labelId/delete-label',   cardController.deleteLabel);
router.put('/:workspaceId/:boardId/:listId/:cardId/:labelId/update-label',   cardController.updateLabel);
router.post('/:workspaceId/:boardId/:listId/:cardId/create-label',   cardController.createLabel);
router.post('/:workspaceId/:boardId/:listId/:cardId/add-member',   cardController.addMember);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:memberId/delete-member',   cardController.deleteMember);
router.post('/create',   cardController.create);
router.get('/:workspaceId/:boardId/:listId/:cardId',   cardController.getCard);
router.get('/:workspaceId/:boardId/:listId',   cardController.getAllCards);
router.put('/:workspaceId/:boardId/:listId/:cardId',   cardController.update);
router.post('/:workspaceId/:boardId/:listId/:cardId/add-comment',   cardController.addComment);
router.put('/:workspaceId/:boardId/:listId/:cardId/:commentId',  cardController.updateComment);
router.delete('/:workspaceId/:boardId/:listId/:cardId/:commentId',  cardController.deleteComment);
module.exports = router;